### ISSUE TITLE
OpenGL Debug Output Support

### ISSUE THREAD

**Issue by fhaust** [haskell-opengl/OpenGLRaw#24]
How hard would it be to support http://www.opengl.org/wiki/Debug_Output ?

Apparently it is (finally) in Core in OpenGL 4.3. Supporting this extensions would relieve the programmer of manually getting OpenGL errors.

**Comment by haraldsteinlechner** [comment]
Any news on this? i mean, OpenGLRawgen seems nice but since the module seems to be commented out i was wondering if there is a version out there supporting debug output (out of the box)?

**Comment by svenpanne** [comment]
Nothing which would work out of the box from my side (OpenGLRaw), but I'm currently working on generating most of this package automatically, too (see my last commits), just like Lars (OpenGLRawGen) and Edward (gl) do. Being one of the Haskell Platform packages, OpenGLRaw is slightly different regarding API stability and build requirements, so neither of the other packages fits perfectly for my purposes.

Depending on how much time I can allocate for Haskell hacking, there might be new release of OpenGLRaw supporting all APIs/versions/profiles in a few weeks.

**Comment by haraldsteinlechner** [comment]
cool :)

**Comment by svenpanne** [comment]
There are core/compatibility modules for OpenGL 4.x now (see issue #5 ), so we can close this.
