### ISSUE TITLE
ghci linker issue when building, even with UseGlXGetProcAddress

### ISSUE THREAD

**Issue by haraldsteinlechner** [haskell-opengl/OpenGLRaw#25]
Hi,

I'm not sure whether this behavior is normal or limited to my machine. I have proprietary nvidida drivers and linux mint 17. 
When i use OpenGLRaw from the debian repositories i end up with OpenGLRaw 1.3 or something http://packages.ubuntu.com/trusty/libghc-openglraw-dev

Since i want a newer version i built from github. When building cabal complaint about missing libGL.so (i have only libGL.so.1 and various other libraries on the system). As a workaround i symlinked libGL.so which is clearly evil. Still, the build and all worked out (building, running), except for ghci which just went into some kind of endless loop after linking OpenGLRaw.

I just discovered, when i use UseGlXGetProcAddress and disable the GL dependence (i.e. don't link against my strange link) all works out fine.

My question now is:
- is this normal or due to strange config on my system
- if abnormal, is there documentation in order not run into this issue, i.e. disabling the gl lib dependency

greetings

**Comment by svenpanne** [comment]
I've never used Mint, I develop/test on Ubuntu 14.04 (with NVIDIA drivers), Ubuntu 14.04 in a VM on Windows (MESA drivers IIRC), and Windows 7, all on x64.  I've got no clue what's going wrong on Mint, I would need detailed steps and the corresponding output (use --verbose=3 with cabal).

It's strange that there is no libGL.so, this seems to be a bug in Mint and/or your local drivers. Looking at my Ubuntu config, things are as follows:

```
svenpanne@svenpanne:~$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

svenpanne@svenpanne:~$ cat /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf 
/usr/lib/nvidia-340
/usr/lib32/nvidia-340

svenpanne@svenpanne:~$ ll /usr/lib/nvidia-340/libGL.so*
lrwxrwxrwx 1 root root      10 Oct 13 20:12 /usr/lib/nvidia-340/libGL.so -> libGL.so.1
lrwxrwxrwx 1 root root      15 Oct 13 20:12 /usr/lib/nvidia-340/libGL.so.1 -> libGL.so.331.79
-rw-r--r-- 1 root root 1163272 May 18  2014 /usr/lib/nvidia-340/libGL.so.331.79
```

Regarding `UseGlXGetProcAddress`: This is on by default, so I don't fully understand that part of your report.

**Comment by svenpanne** [comment]
Any news on this? If there are still issues, the dynamic linker configuration would be interesting.

**Comment by haraldsteinlechner** [comment]
Hi,

i think ubuntu, mint is pretty much the same in this. When watching at your config i found that my driver is older and kind of strange because there is no libGL in the specific lib folder. 

Ah. if glxGetProcAddress is default i don't undertand the probleme anymore. my appearance was that, when linking with ghc, dlsym did not work properly, but in case of getProcAddress this theory breaks.


```
hs@urdar ~ $ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

hs@urdar ~ $  cat /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf 
/usr/lib/nvidia-331
/usr/lib32/nvidia-331
```

and no libGL.so* in /usr/lib/nvidia-331

Atm you can close this one down, since most likely this has to to with my local setup.
Thanks for your support
