### ISSUE TITLE
 Graphics.Rendering.OpenGL.Raw.Functions on 7.10

### ISSUE THREAD

**Issue by paolino** [haskell-opengl/OpenGLRaw#30]
Could you please set an if in the cabal file to regress to -O0 when compiling that module with ghc 7.10?
It eats more than 3GB of memory.

**Comment by phaazon** [comment]
Increase the swap! ;) I’m really not for such a solution. However, a flag could be a good idea. I’ll add that :)

**Comment by paolino** [comment]
well, any user of opengl with less then 3GB is going to crash into this until 7.10.1 is around. 
It would be good to have a workaround. Just to mention cabal install gloss  is going to freeze a lot of machines. How much time do they have to spend to fix it, finding the problem here, break the cabal install chain and probably more. I resolved , but I have to spread the workaround to the end users. And when ghc resolves take the workaround back. It's a ghc bad bug I suppose, but this library is going to pay for it. That's why I think corrupting cabal is the way. YMMV eventually.

**Comment by phaazon** [comment]
I have GHC 7.10.1 installed here, and I don’t think corrupting a cabal file that would kill performance is a good idea.

**Comment by paolino** [comment]
If it would kill permormance it's a problem really.

paolino

2015-04-30 23:49 GMT+02:00 Dimitri Sabadie <notifications@github.com>:

**Comment by paolino** [comment]
how much memory does it take to compile on 7.10.1 ?

**Comment by phaazon** [comment]
A lot :D Something like 3GB, yeah.

**Comment by paolino** [comment]
I resolved splitting Functions.hs. And get a ticked opened on ghc trac.

2015-05-01 0:51 GMT+02:00 Dimitri Sabadie <notifications@github.com>:

**Comment by phaazon** [comment]
Great! May you paste the link to the issue? :)

**Comment by svenpanne** [comment]
I've uploaded a new version of OpenGLRaw (2.5.0.0) to Hackage today, it might help a bit with the memory problems. Could you try it and report if things improved for you?

**Comment by paolino** [comment]
yes, now I'm on a 32 bit OS and it 2.4.1 compiles fine under 2GB. When I
arrive home I will check the 2.5.0 on the 64bit. Both with 7.10.1 obviously.

regards

cyl, paolino

2015-05-03 16:41 GMT+02:00 Sven Panne <notifications@github.com>:

**Comment by svenpanne** [comment]
OK, 2.5.0.0 really seems to improve things a bit (2.3 - 2.6GB on 64bit according to https://mail.haskell.org/pipermail/glasgow-haskell-users/2015-May/025859.html), so I think I'll close this issue. The rest has to be done on the GHC side (and in Haddock, but that's a different story).
