### ISSUE TITLE
Expected type GLint, actual type GLenum

### ISSUE THREAD

**Issue by bwroga** [haskell-opengl/OpenGLRaw#31]
I am getting compile errors when I try to pass a GLenum as the third parameter to glSamplerParameteri and glTexParameteri. It makes sense to me... GLenum is a CUint and these functions expect a CInt, but it's unexpected after reading the OpenGL docs. 

Do you recommend using fromIntegral to convert from GLuint to GLint? Or is there another solution?

I am using OpenGLRaw 2.5 on Ubuntu 12.04.

**Comment by svenpanne** [comment]
I'm not sure which OpenGL docs you've read, but the OpenGL specification has always been very explicit about the meaning of the suffixes, see e.g. section 2.2 ("Command Syntax") in the OpenGL 4.5 spec: An "i" means "int", so the last parameter to `glSamplerParameteri` has to be a `GLint`, which is consistent with all the other `glFooParameteri` API entries (and the C header). Note that there is no suffix for `GLenum` at all, which can be glossed over in C/C++, but in Haskell you have to convert explicitly with `fromIntegral` if you want to pass a `GLenum`.

Furthermore, the OpenGLRaw package is generated almost completely from the official [XML description](https://github.com/svenpanne/OpenGL-Registry/blob/master/gl.xml) of the OpenGL API, so it must be correct. :wink:

**Comment by bwroga** [comment]
That makes sense, thanks. I have never programmed in C/C++ and didn't understand why the documentation showed GLenums being passed to functions that expected GLints.
