### ISSUE TITLE
Missing (or bad) C library: GL

### ISSUE THREAD

**Issue by stla** [haskell-opengl/OpenGLRaw#37]
Hello,

 I'm using Ubuntu 18.04 and I cannot install OpenGLRaw, because of:

> Missing (or bad) C library: GL

I've spent a couple of hours with Google to find a solution but nothing has worked (I've seen [this post](https://github.com/haskell-opengl/OpenGLRaw/issues/34)). I have installed and reinstalled some libraries, that didn't solve the problem.

**Comment by stla** [comment]
Oh I think I've just found a solution ! I made a symbolic link:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1.0.0 /usr/lib/x86_64-linux-gnu/libGL.so`

And then my computer is currently installing OpenGLRaw !

**Comment by svenpanne** [comment]
Nice to hear that things are working for you now, but manually creating a symlink is quite a hack. It looks like you're missing the `libglvnd-dev` package, see https://packages.ubuntu.com/bionic/libglvnd-dev, which contains various symlinks. The NVIDIA drivers already contain all symlinks without any additional `-dev` packages, see e.g. https://packages.ubuntu.com/bionic/nvidia-340. No idea why Ubuntu packages things differently for non-NVIDIA drivers...
