### ISSUE TITLE
Missing (or bad) C library: GL, Ubuntu

### ISSUE THREAD

**Issue by CTHULHU-Jesus** [haskell-opengl/OpenGLRaw#38]
when I run
$cabal install OpenGLRaw
I get the error 
Configuring library for OpenGLRaw-3.3.4.0..
cabal: Missing dependency on a foreign library:
* Missing (or bad) C library: GL
I have tried re installing mesa-common-dev, freeglut3-dev,  libglu1-mesa-dev
but it still doesn't work.

**Comment by svenpanne** [comment]
Without a crystal ball it is quite hard to guess what's going on... :wink: Some details about your platform, the versions of the tools involved, your drivers/headers, if this is a nix-based build or not etc. are needed. The reason for needing all those details is that different setups vary in extremely surprising ways, platform/driver vendors and packagers have been _very_ creative in th the OpenGL area for no good reason.

Perhaps you can have a look at #37 and #34, those solved issues may contain a solution for you.

**Comment by CTHULHU-Jesus** [comment]
Thank you, I had looked at #37 but #34 seems to have some bread crumbs.
I ran 
```
echo 'int main(int argc, char** argv) { return 0; }' > blah.c
gcc blah.c -lGL
```
and got the error 
```
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
```

**Comment by svenpanne** [comment]
OK. if you can't even link a trivial C program with `-lGL`, you'll have to find out which package you are missing. For my Ubuntu 19.10 the file in question is `/usr/lib/x86_64-linux-gnu/libGL.so`, which is provided by the `libglvnd-dev` package.

**Comment by CTHULHU-Jesus** [comment]
Install installing ` libglvnd-dev` didn't work but installing `nvidia-340` did for some reason. Thank you.
