### ISSUE TITLE
add deprecation pragmas for deprecated opengl calls

### ISSUE THREAD

**Issue by dagit** [haskell-opengl/OpenGLRaw#4]
It would be nice if these only turn on when you import the calls from a module name that implies a specific opengl version.  So if you import from something like Core2 there is no warning, but if imported from Core31 the warning goes off.

But, the bottom line and intent is that people get compile warnings when using old stuff unless they really meant to use the old stuff.

**Comment by svenpanne** [comment]
With all the core/compatibility modules available now (see issue #5), I don't think we need any kind of deprecation mechanism,
