### ISSUE TITLE
OpenGLRaw error

### ISSUE THREAD

**Issue by swagmanfrenchie** [haskell-opengl/OpenGLRaw#40]
Hello, I've been trying to install gloss for a game that i am creating however i cam across this error with OpenGLRaw. I've been looking everywhere on the internet and i could not find a single solution for this.

C:\Users\mahmo>cabal install gloss
Resolving dependencies...
Build profile: -w ghc-8.10.2 -O1
In order, the following will be built (use -v for more details):
 - OpenGLRaw-3.3.4.0 (lib) (requires build)
 - GLURaw-2.0.0.4 (lib) (requires build)
 - OpenGL-3.0.3.0 (lib) (requires build)
 - GLUT-2.7.0.15 (lib) (requires build)
 - gloss-rendering-1.13.1.1 (lib) (requires build)
 - gloss-1.13.2.1 (lib) (requires build)
Starting     OpenGLRaw-3.3.4.0 (lib)
Building     OpenGLRaw-3.3.4.0 (lib)

Failed to build OpenGLRaw-3.3.4.0.
Build log (
C:\Users\mahmo\AppData\Roaming\cabal\logs\ghc-8.10.2\OpenGLRaw-3.3.4.0-2619472a55bb3c9f5107fd3ea20e2943351a0282.log
):
Preprocessing library for OpenGLRaw-3.3.4.0..
Building library for OpenGLRaw-3.3.4.0..
[  1 of 617] Compiling Graphics.GL.Groups ( src\Graphics\GL\Groups.hs, dist\build\Graphics\GL\Groups.o )
[  2 of 617] Compiling Graphics.GL.Types ( src\Graphics\GL\Types.hs, dist\build\Graphics\GL\Types.o )
ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe
cabal.exe: Failed to build OpenGLRaw-3.3.4.0 (which is required by
gloss-1.13.2.1). See the build log above for details.

**Comment by svenpanne** [comment]
I don't use cabal (only stack), so I don't have a clue where it puts the detailed compilation log, but I need to see that to get an idea what's going wrong. Is the output above truncated/edited? It doesn't really make sense that the linker is called after 2 of 617 modules...

**Comment by swagmanfrenchie** [comment]
![image](https://user-images.githubusercontent.com/26778498/104034308-9df01c80-51c8-11eb-9c63-b304dfdacf97.png)

i havent edited out anything.

and here is the compilation log:

Preprocessing library for OpenGLRaw-3.3.4.0..
Building library for OpenGLRaw-3.3.4.0..
[  1 of 617] Compiling Graphics.GL.Groups ( src\Graphics\GL\Groups.hs, dist\build\Graphics\GL\Groups.o )
[  2 of 617] Compiling Graphics.GL.Types ( src\Graphics\GL\Types.hs, dist\build\Graphics\GL\Types.o )
ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe

**Comment by svenpanne** [comment]
Alas, that's not enough to diagnose the problem, perhaps the file `C:\Users\mahmo\AppData\Roaming\cabal\logs\ghc-8.10.2\OpenGLRaw-3.3.4.0-2619472a55bb3c9f5107fd3ea20e2943351a0282.log` mentioned in the output contains more information? Cabal (and stack) output only very superficial information, the details are normally in some log files...

**Comment by swagmanfrenchie** [comment]
C:\Users\mahmo\AppData\Roaming\cabal\logs\ghc-8.10.2\OpenGLRaw-3.3.4.0-2619472a55bb3c9f5107fd3ea20e2943351a0282.log

This file is what i just showed so it does not mention much, so im quite confused.

**Comment by svenpanne** [comment]
What I need is a log where you can see the exact invocation of GHC, the linker, etc. Without that, there's not much I can do. What  you've showed so far is the console output of the compilation, not the build log, that's something completely different.

**Comment by swagmanfrenchie** [comment]
Any idea as to where I would find them because I've looked under C:\Users\mahmo\AppData\Roaming\cabal\logs\ghc-8.10.2 and there doesn't seem to be a detailed one.

**Comment by svenpanne** [comment]
Without more details there is not much I can do, so I'll close this issue. Feel free to re-open it (or create a new issue) when there is more information available.
