### ISSUE TITLE
OpenGLRaw fails to build with 'split-sections: True' on Windows/amd64 10

### ISSUE THREAD

**Issue by Mjnd** [haskell-opengl/OpenGLRaw#41]
Hello,
I've tried to compile OpenGLRaw v3.3.4.0 using GHC and Cabal, with `split-sections: True` enabled on cabal/config in Windows/amd64 v10, but the process fails with the following message (similar in both versions of GHC/Cabal used):

```
[...]
[617 of 617] Compiling Graphics.GL      ( src\Graphics\GL.hs, dist\build\Graphics\GL.o )
C:\Program Files\GHC-8.6.5\lib\../mingw/bin\ld.exe: dist\build\HSOpenGLRaw-3.3.4.0-LbLzAQRjVYc4uE4RgrZjxe.o: too many sections (67760)
C:\Program Files\GHC-8.6.5\lib\../mingw/bin\ld.exe: final link failed: File too big
cabal: Leaving directory 'C:\Users\<user>\AppData\Local\Temp\cabal-tmp-3204\OpenGLRaw-3.3.4.0'
cabal.exe: Error: some packages failed to install:
GLURaw-2.0.0.4-10KgZckuPJf43gcTUy3nI3 depends on GLURaw-2.0.0.4 which failed
to install.
OpenGL-3.0.2.2-OUWLGivwn055CFreNyTxD depends on OpenGL-3.0.2.2 which failed to
install.
OpenGLRaw-3.3.4.0-LbLzAQRjVYc4uE4RgrZjxe failed during the building phase. The
exception was:
ExitFailure 1
```

The same problem also appears using the last Haskell Platform installer (HaskellPlatform-8.6.5-core-x86_64-setup.exe).

Software used:
- GHC binary packages for Windows (x86_64), v8.6.5 and v8.10.4, downloaded from https://www.haskell.org/ghc/download.html
- Cabal binary packages for Windows (x86_64), v2.4.0.0 and v3.2.0.0 downloaded from https://www.haskell.org/cabal/download.html

**Comment by svenpanne** [comment]
AFAICT there is not much I can do on the library side, perhaps open an issue for GHC?

**Comment by Mjnd** [comment]
Done, thank you.
https://gitlab.haskell.org/ghc/ghc/-/issues/20682
