### ISSUE TITLE
Compatibility with GHC 9.2 and transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [haskell-opengl/OpenGLRaw#42]
`master` already seems to build with GHC 9.2 – could you make a release or a revision?

Compatibility with the latest `transformers` will require another bump (and possibly code changes – I didn't check).

**Comment by svenpanne** [comment]
I'll do that. When I finally figure out how to generate GitHub Actions workflows from .cabal files... :cry:

**Comment by sjakobi** [comment]
> When I finally figure out how to generate GitHub Actions workflows from .cabal files...

Please see my email on Haskell Cafe! :)

**Comment by svenpanne** [comment]
Done. The binding itself needs to be updated, too, the registry has changed its schema. But this will be done in separate changes, so a fresh version can be uploaded to Hackage right now.
