### ISSUE TITLE
Make Core33, Core40 and Core41

### ISSUE THREAD

**Issue by Laar** [haskell-opengl/OpenGLRaw#5]
There are only core modules for GL 3.1 and 3.2, though for developing the OpenGL package and other people using the bindings it is very useful to have a module to import having all the functions for the newer OpenGL versions. 
If people like it it might also be worth the effort to create such modules for previous versions (3.0, 2.x and 1.x) .

**Comment by svenpanne** [comment]
OpenGLRaw contains automatically generated modules for OpenGL 1.0 - 4.5 now, so this issue can be closed. There are a few rough edges still: The calling convention for the callbacks need to be checked, and the extensions are not yet automatically generated, nevertheless it is already a big improvement compared to the previous state (see e.g. the comments for the API entries). I'll make a hackage release when things are a bit more polished.
